env_path: 'C:/Unity Projects/Hide and Seek/Environments/2.0/Env_Nav_3_Seekers_Human_Player/Hide and Seek'
checkpoint_to_load:
checkpoint_save_name: "Human_play_Nav"
id_to_name: {1: 'Hider 0'}
total_episodes: 100
max_steps: 300
device_idx: 0
hostname: 'localhost'