env_path: '../Env_Linux_Nav_3_Seekers_Big_Rocks_No_Waiting_Time'
checkpoint_to_load: "Checkpoint_Nav_Distributed_RL.pth.tar"
checkpoint_to_save: "Checkpoint_Nav_Distributed_RL.pth.tar"
name_tensorboard: "CNN_LSTM_DQN_Nav_Distributed_RL_Hider"
memory_size: 150
device_idx: [4,5,6,7]
resume: False
total_epochs: 40000
max_steps: 100
batch_size: 20
time_step: 16
learning_rate: 0.00025
gamma: 0.99
initial_epsilon: 1.0
final_epsilon: 0.1
epsilon_vanish_rate: 0.9999
performance_display_interval(epochs): 5
checkpoint_save_interval(epochs): 200
actor_update_freq(epochs): 5
target_update_freq(epochs): 40