checkpoint_to_load: "Checkpoint_Nav_Human_Play.pth.tar"
device_idx: [3,4,5,6,7]
id_to_name: {3: 'Hider 0'}
name_tensorboard: "CNN_LSTM_DQN_Nav_RL_Hider"
cnn_out_size: [500]
atten_size: [2]
lstm_hidden_size: [512]
action_shape: [[3,3]]
action_out_size: [32]
env_path: '../Env_Linux_Nav_3_Seekers_Big_Rocks_No_Waiting_Time/Hide and Seek'
total_episodes_each_actor: 200
total_epochs: 2000
max_steps: 60
resume: False
checkpoint_to_save: "Checkpoint_Nav_Human_Play_RL.pth.tar"
batch_size: 2
time_step: 5
learning_rate: 0.00025
gamma: 0.99
initial_epsilon: 1.0
final_epsilon: 0.1
epsilon_vanish_rate: 0.9999
memory_size: 5
performance_display_interval(epochs): 5
checkpoint_save_interval(epochs): 5
actor_update_freq(epochs): 1
target_update_freq(epochs): 10

