memory_to_load: "Human_play_Nav_2022-09-30_01-18.pth.tar"
checkpoint_to_load: "Checkpoint_Nav_Human_Play.pth.tar"
device_idx: [0]
name_tensorboard: "CNN_LSTM_DQN_Nav_Hider"
cnn_out_size: [500]
atten_size: [15]
lstm_hidden_size: [512]
action_shape: [[3,3]]
action_out_size: [32]
env_path: 'C:/Unity Projects/Hide and Seek/Env_Nav/Hide and Seek'
total_epochs: 2000
max_steps: 100
resume: False
checkpoint_to_save: "Checkpoint_Nav_Human_Play.pth.tar"
batch_size: 10
time_step: 20
learning_rate: 0.00025
gamma: 0.99
checkpoint_save_interval: 10
target_update_freq(epochs): 10