env_path: '../../Env_Linux_Nav_3_Seekers_Big_Rocks_No_Waiting_Time'
checkpoint_to_load: "Checkpoint_Nav_Distributed_RL_Debug.pth.tar"
checkpoint_to_save: "Checkpoint_Nav_Distributed_RL_Debug.pth.tar"
name_tensorboard: "CNN_LSTM_DQN_Nav_Distributed_RL_Hider_Debug"
memory_size: 4
device_idx: [0]
resume: False
total_epochs: 200
max_steps: 130
batch_size: 1
num_batch_per_learner: 2
sequence_length: 3
initial_learning_rate: 0.0005
learning_rate_gamma: 0.2
learning_rate_step_size: 50
epsilon_gamma: 0.99
initial_epsilon: 1.0
final_epsilon: 0.1
epsilon_vanish_rate: 0.9999
performance_display_interval(epochs): 5
checkpoint_save_interval(epochs): 5
actor_update_freq(epochs): 1
